version: '2'

services:
   db:
     image: mysqltcc
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: tcc
       MYSQL_DATABASE: tcc

   web:
     links:
       - db
     image: docker.local/michaeldim/alpine-nginx-php
     ports:
       - "80:80"
     volumes:
       - ./app:/var/www/
